#!/usr/bin/env bash

# AutoGrantApp.sh
# Injects a builtin root allowlist into KWS/KernelSU at CI build time.
#
# This script runs AFTER install_ksu clones KernelSU into $KSRC/KernelSU.
# It patches two files inside that freshly-cloned tree:
#   1. kernel/policy/builtin_allowlist.h  (generated from BUILTIN_APPS below)
#   2. kernel/policy/allowlist.c          (patched to load the header)
#
# To add/remove apps, edit BUILTIN_APPS below and push to the builder repo.
# No changes to the KernelSU repo are ever needed.

# ── Trusted apps ─────────────────────────────────────────────────────────────
BUILTIN_APPS=(
    in.hridayan.ashell
    bin.mt.plus.canary
    org.swiftapps.swiftbackup
    com.kanagawa.yamada.darjeeling
)
# ─────────────────────────────────────────────────────────────────────────────

log "Applying AutoGrantApp (Builtin Root Allowlist) patch..."

# ── Resolve KernelSU directory ────────────────────────────────────────────────
if [[ -d "$KSRC/KernelSU" ]]; then
    KSU_DIR="$KSRC/KernelSU"
else
    log "[ERROR] KernelSU directory not found at $KSRC/KernelSU!"
    exit 1
fi

HEADER="$KSU_DIR/kernel/policy/builtin_allowlist.h"
ALLOWLIST_C="$KSU_DIR/kernel/policy/allowlist.c"

# ── Sanity check ──────────────────────────────────────────────────────────────
if [[ ! -f "$ALLOWLIST_C" ]]; then
    log "[ERROR] allowlist.c not found at $ALLOWLIST_C!"
    exit 1
fi

# ── 1. Generate builtin_allowlist.h ──────────────────────────────────────────
log "  Generating $HEADER..."

cat > "$HEADER" << 'HEADER_START'
/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * SuiKernel - Builtin Root Allowlist
 *
 * Auto-generated by AutoGrantApp.sh at CI build time.
 * Edit AutoGrantApp.sh in the builder repo to change this list.
 *
 * These apps are pre-seeded into the KWS allowlist at kernel level,
 * granting root automatically without needing a manager-app toggle.
 */

#ifndef __KSU_BUILTIN_ALLOWLIST_H
#define __KSU_BUILTIN_ALLOWLIST_H

#include <linux/types.h>

struct builtin_allowed_app {
	const char *package;
};

/* Trusted apps - auto-granted root */
static const struct builtin_allowed_app ksu_builtin_allowed_apps[] = {
HEADER_START

for pkg in "${BUILTIN_APPS[@]}"; do
    printf '\t{ "%s" },\n' "${pkg}"
done >> "$HEADER"

cat >> "$HEADER" << 'HEADER_END'
};

#define KSU_BUILTIN_ALLOWED_COUNT \
	(sizeof(ksu_builtin_allowed_apps) / sizeof(ksu_builtin_allowed_apps[0]))

static inline bool ksu_is_builtin_allowed_package(const char *key)
{
	size_t i;

	if (!key)
		return false;

	for (i = 0; i < KSU_BUILTIN_ALLOWED_COUNT; i++) {
		if (strncmp(key, ksu_builtin_allowed_apps[i].package,
			    KSU_MAX_PACKAGE_NAME) == 0)
			return true;
	}
	return false;
}

#endif /* __KSU_BUILTIN_ALLOWLIST_H */
HEADER_END

log "  ✅ Generated $(wc -l < "$HEADER") lines in builtin_allowlist.h"

# ── 2. Patch allowlist.c ─────────────────────────────────────────────────────
# Guard: skip if already patched (idempotent for re-runs)
if grep -q "builtin_allowlist.h" "$ALLOWLIST_C"; then
    log "  ℹ️  allowlist.c already patched, skipping."
else
    log "  Patching $ALLOWLIST_C..."

    # 2a. Inject #include right after the existing app_profile.h include
    sed -i 's|#include "policy/app_profile.h"|#include "policy/app_profile.h"\n#include "policy/builtin_allowlist.h"|' "$ALLOWLIST_C"

    # 2b. Inject builtin fast-path into __ksu_is_allow_uid(), just before "return false;"
    #     We target the last "return false;" inside the function (after the rcu loop).
    #     Use a Python one-liner for reliable multi-line insertion.
    python3 - "$ALLOWLIST_C" << 'PYEOF'
import sys, re

path = sys.argv[1]
with open(path, 'r') as f:
    src = f.read()

# The injection marker: the closing of __ksu_is_allow_uid's rcu block
OLD = '''\
    rcu_read_unlock();

    return false;
}

bool __ksu_is_allow_uid_for_current'''

NEW = '''\
    rcu_read_unlock();

    /* Builtin fast-path: grant root to any UID whose package name is in
     * the compile-time ksu_builtin_allowed_apps list. */
    rcu_read_lock();
    hash_for_each_possible_rcu (allow_list, p, list, uid) {
        if (uid == p->profile.curr_uid &&
            ksu_is_builtin_allowed_package(p->profile.key)) {
            rcu_read_unlock();
            return true;
        }
    }
    rcu_read_unlock();

    return false;
}

bool __ksu_is_allow_uid_for_current'''

if OLD not in src:
    print("[AutoGrantApp] WARNING: Could not find injection point in __ksu_is_allow_uid(). Skipping fast-path.")
    sys.exit(0)

src = src.replace(OLD, NEW, 1)

# Seed builtin apps inside ksu_load_allow_list(), just before the final
# ksu_show_allow_list() + filp_close() block.
OLD2 = '''\
    ksu_show_allow_list();
    filp_close(fp, 0);
    if (version < KSU_APP_PROFILE_VER)
        ksu_persistent_allow_list();
    return;

exit:'''

NEW2 = '''\
    /* Seed builtin allowed apps — always granted root regardless of what
     * the on-disk allowlist says. Existing entries get their allow_su
     * flag forced to true; new entries are inserted with UID=0 as a
     * placeholder (ksud will fill in the real UID on next app sync). */
    {
        size_t bi;
        kernel_cap_t full_cap = CAP_FULL_SET;

        for (bi = 0; bi < KSU_BUILTIN_ALLOWED_COUNT; bi++) {
            struct app_profile builtin_profile;
            bool found = false;
            struct perm_data *bp;

            rcu_read_lock();
            hash_for_each_possible_rcu (allow_list, bp, list, 0) {
                if (strncmp(bp->profile.key,
                            ksu_builtin_allowed_apps[bi].package,
                            KSU_MAX_PACKAGE_NAME) == 0) {
                    found = true;
                    break;
                }
            }
            rcu_read_unlock();

            if (found) {
                if (!bp->profile.allow_su) {
                    bp->profile.allow_su = true;
                    bp->profile.rp_config.use_default = true;
                    pr_info("builtin_allowlist: upgraded %s to allow_su\\n",
                            ksu_builtin_allowed_apps[bi].package);
                }
                continue;
            }

            memset(&builtin_profile, 0, sizeof(builtin_profile));
            builtin_profile.version = KSU_APP_PROFILE_VER;
            strscpy(builtin_profile.key,
                    ksu_builtin_allowed_apps[bi].package,
                    KSU_MAX_PACKAGE_NAME);
            builtin_profile.curr_uid              = 0;
            builtin_profile.allow_su              = true;
            builtin_profile.rp_config.use_default = true;
            memcpy(&builtin_profile.rp_config.profile.capabilities.effective,
                   &full_cap, sizeof(__u64));
            memcpy(&builtin_profile.rp_config.profile.capabilities.permitted,
                   &full_cap, sizeof(__u64));
            strscpy(builtin_profile.rp_config.profile.selinux_domain,
                    KSU_DEFAULT_SELINUX_DOMAIN, KSU_SELINUX_DOMAIN);

            pr_info("builtin_allowlist: seeding %s\\n",
                    ksu_builtin_allowed_apps[bi].package);
            ksu_set_app_profile(&builtin_profile);
        }
    }

    ksu_show_allow_list();
    filp_close(fp, 0);
    if (version < KSU_APP_PROFILE_VER)
        ksu_persistent_allow_list();
    return;

exit:'''

if OLD2 not in src:
    print("[AutoGrantApp] WARNING: Could not find ksu_load_allow_list injection point. Skipping seed block.")
else:
    src = src.replace(OLD2, NEW2, 1)

with open(path, 'w') as f:
    f.write(src)

print("[AutoGrantApp] allowlist.c patched successfully.")
PYEOF

    log "  ✅ allowlist.c patched."
fi

# ── 3. Summary ────────────────────────────────────────────────────────────────
log "✅ AutoGrantApp patch complete. Builtin apps:"
for pkg in "${BUILTIN_APPS[@]}"; do
    log "   • $pkg"
done
