#!/usr/bin/env bash

# AutoGrantApp.sh
# Injects a builtin root allowlist into KWS/KernelSU at CI build time.
#
# This script runs AFTER install_ksu clones KernelSU into $KSRC/KernelSU.
# It patches two files inside that freshly-cloned tree:
#   1. kernel/policy/builtin_allowlist.h  (generated from BUILTIN_APPS below)
#   2. kernel/policy/allowlist.c          (patched to load the header)
#
# To add/remove apps, edit BUILTIN_APPS below and push to the builder repo.
# No changes to the KernelSU repo are ever needed.

# ── Trusted apps ─────────────────────────────────────────────────────────────
BUILTIN_APPS=(
    in.hridayan.ashell
    bin.mt.plus.canary
    org.swiftapps.swiftbackup
    com.kanagawa.yamada.darjeeling
)
# ─────────────────────────────────────────────────────────────────────────────

log "Applying AutoGrantApp (Builtin Root Allowlist) patch..."

# ── Resolve KernelSU directory ────────────────────────────────────────────────
if [[ -d "$KSRC/KernelSU" ]]; then
    KSU_DIR="$KSRC/KernelSU"
else
    log "[ERROR] KernelSU directory not found at $KSRC/KernelSU!"
    exit 1
fi

HEADER="$KSU_DIR/kernel/policy/builtin_allowlist.h"
ALLOWLIST_C="$KSU_DIR/kernel/policy/allowlist.c"

# ── Sanity check ──────────────────────────────────────────────────────────────
if [[ ! -f "$ALLOWLIST_C" ]]; then
    log "[ERROR] allowlist.c not found at $ALLOWLIST_C!"
    exit 1
fi

# ── 1. Generate builtin_allowlist.h ──────────────────────────────────────────
log "  Generating $HEADER..."

cat > "$HEADER" << 'HEADER_START'
/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * SuiKernel - Builtin Root Allowlist
 *
 * Auto-generated by AutoGrantApp.sh at CI build time.
 * Edit AutoGrantApp.sh in the builder repo to change this list.
 *
 * These apps are pre-seeded into the KWS allowlist at kernel level,
 * granting root automatically without needing a manager-app toggle.
 */

#ifndef __KSU_BUILTIN_ALLOWLIST_H
#define __KSU_BUILTIN_ALLOWLIST_H

#include <linux/types.h>

struct builtin_allowed_app {
	const char *package;
};

/* Trusted apps - auto-granted root */
static const struct builtin_allowed_app ksu_builtin_allowed_apps[] = {
HEADER_START

for pkg in "${BUILTIN_APPS[@]}"; do
    printf '\t{ "%s" },\n' "${pkg}"
done >> "$HEADER"

cat >> "$HEADER" << 'HEADER_END'
};

#define KSU_BUILTIN_ALLOWED_COUNT \
	(sizeof(ksu_builtin_allowed_apps) / sizeof(ksu_builtin_allowed_apps[0]))

static inline bool ksu_is_builtin_allowed_package(const char *key)
{
	size_t i;

	if (!key)
		return false;

	for (i = 0; i < KSU_BUILTIN_ALLOWED_COUNT; i++) {
		if (strncmp(key, ksu_builtin_allowed_apps[i].package,
			    KSU_MAX_PACKAGE_NAME) == 0)
			return true;
	}
	return false;
}

#endif /* __KSU_BUILTIN_ALLOWLIST_H */
HEADER_END

log "  ✅ Generated $(wc -l < "$HEADER") lines in builtin_allowlist.h"

# ── 2. Patch allowlist.c ─────────────────────────────────────────────────────
# Guard: skip if already patched (idempotent for re-runs)
if grep -q "builtin_allowlist.h" "$ALLOWLIST_C"; then
    log "  ℹ️  allowlist.c already patched, skipping."
else
    log "  Patching $ALLOWLIST_C..."

    # 2a. Inject #include right after the existing allowlist.h include
    sed -i 's|#include "policy/allowlist.h"|#include "policy/allowlist.h"\n#include "policy/builtin_allowlist.h"|' "$ALLOWLIST_C"

    # 2b. Inject builtin fast-path into __ksu_is_allow_uid(), just before "return false;"
    #     We target the last "return false;" inside the function (after the rcu loop).
    #     Use a Python one-liner for reliable multi-line insertion.
    python3 - "$ALLOWLIST_C" << 'PYEOF'
import sys, re

path = sys.argv[1]
with open(path, 'r') as f:
    src = f.read()

# The injection marker: the closing of __ksu_is_allow_uid's rcu block
OLD_PATTERN = re.compile(r"(\s*)rcu_read_unlock\(\);\n\n\s*return false;\n\}\n\nbool __ksu_is_allow_uid_for_current")

def repl1(m):
    i = m.group(1)
    return f"""{i}rcu_read_unlock();

{i}/* Builtin fast-path: grant root to any UID whose package name is in
{i} * the compile-time ksu_builtin_allowed_apps list. */
{i}rcu_read_lock();
{i}hash_for_each_possible_rcu (allow_list, p, list, uid) {{
{i}    if (uid == p->profile.curr_uid &&
{i}        ksu_is_builtin_allowed_package(p->profile.key)) {{
{i}        rcu_read_unlock();
{i}        return true;
{i}    }}
{i}}}
{i}rcu_read_unlock();

{i}return false;
}}

bool __ksu_is_allow_uid_for_current"""

if not OLD_PATTERN.search(src):
    print("[AutoGrantApp] WARNING: Could not find injection point in __ksu_is_allow_uid(). Skipping fast-path.")
else:
    src = OLD_PATTERN.sub(repl1, src, count=1)

# Seed builtin apps inside ksu_load_allow_list(), just before the final
# ksu_show_allow_list() + filp_close() block.
OLD2_PATTERN = re.compile(r"(\s*)ksu_show_allow_list\(\);\n\s*filp_close\(fp, 0\);\n\s*if \(version < KSU_APP_PROFILE_VER\)\n\s*ksu_persistent_allow_list\(\);\n\s*return;\n\nexit:")

def repl2(m):
    i = m.group(1)
    return f"""{i}/* Seed builtin allowed apps — always granted root regardless of what
{i} * the on-disk allowlist says. Existing entries get their allow_su
{i} * flag forced to true; new entries are inserted with UID=0 as a
{i} * placeholder (ksud will fill in the real UID on next app sync). */
{i}{{
{i}    size_t bi;
{i}    kernel_cap_t full_cap = CAP_FULL_SET;
{i}
{i}    for (bi = 0; bi < KSU_BUILTIN_ALLOWED_COUNT; bi++) {{
{i}        struct app_profile builtin_profile;
{i}        bool found = false;
{i}        struct perm_data *bp;
{i}
{i}        rcu_read_lock();
{i}        hash_for_each_possible_rcu (allow_list, bp, list, 0) {{
{i}            if (strncmp(bp->profile.key,
{i}                        ksu_builtin_allowed_apps[bi].package,
{i}                        KSU_MAX_PACKAGE_NAME) == 0) {{
{i}                found = true;
{i}                break;
{i}            }}
{i}        }}
{i}        rcu_read_unlock();
{i}
{i}        if (found) {{
{i}            if (!bp->profile.allow_su) {{
{i}                bp->profile.allow_su = true;
{i}                bp->profile.rp_config.use_default = true;
{i}                pr_info("builtin_allowlist: upgraded %s to allow_su\\n",
{i}                        ksu_builtin_allowed_apps[bi].package);
{i}            }}
{i}            continue;
{i}        }}
{i}
{i}        memset(&builtin_profile, 0, sizeof(builtin_profile));
{i}        builtin_profile.version = KSU_APP_PROFILE_VER;
{i}        strscpy(builtin_profile.key,
{i}                ksu_builtin_allowed_apps[bi].package,
{i}                KSU_MAX_PACKAGE_NAME);
{i}        builtin_profile.curr_uid              = 0;
{i}        builtin_profile.allow_su              = true;
{i}        builtin_profile.rp_config.use_default = true;
{i}        memcpy(&builtin_profile.rp_config.profile.capabilities.effective,
{i}               &full_cap, sizeof(__u64));
{i}        memcpy(&builtin_profile.rp_config.profile.capabilities.permitted,
{i}               &full_cap, sizeof(__u64));
{i}        strscpy(builtin_profile.rp_config.profile.selinux_domain,
{i}                KSU_DEFAULT_SELINUX_DOMAIN, KSU_SELINUX_DOMAIN);
{i}
{i}        pr_info("builtin_allowlist: seeding %s\\n",
{i}                ksu_builtin_allowed_apps[bi].package);
{i}        ksu_set_app_profile(&builtin_profile);
{i}    }}
{i}}}
{i}
{i}ksu_show_allow_list();
{i}filp_close(fp, 0);
{i}if (version < KSU_APP_PROFILE_VER)
{i}    ksu_persistent_allow_list();
{i}return;
{i}
{i}exit:"""

if not OLD2_PATTERN.search(src):
    print("[AutoGrantApp] WARNING: Could not find ksu_load_allow_list injection point. Skipping seed block.")
else:
    src = OLD2_PATTERN.sub(repl2, src, count=1)

with open(path, 'w') as f:
    f.write(src)

print("[AutoGrantApp] allowlist.c patched successfully.")
PYEOF

    log "  ✅ allowlist.c patched."
fi

# ── 3. Summary ────────────────────────────────────────────────────────────────
log "✅ AutoGrantApp patch complete. Builtin apps:"
for pkg in "${BUILTIN_APPS[@]}"; do
    log "   • $pkg"
done
